exec proc_exception1('test');